[tool.black]
line-length = 120
target-version = ["py312"]
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 120
py_version = 312

[tool.mypy]
ignore_missing_imports = true